### ISSUE TITLE
Hash value length maybe less than 8 sometimes when using crc32 crypto.

### ISSUE THREAD

**Issue by jqqjj** [codingsince1985/checksum#3]
Hash value length maybe less than 8 sometimes when using crc32 crypto.
For the file below, it's crc32 value string is "4a40c0d" when using crc32 crypto. it's wrong,the right value is "04a40c0d"

[https://img.lovefate.com/file/storage/upload/fb/ca/04a40c0d.png](url)

Need to fixed it.

**Comment by codingsince1985** [comment]
thank you @jqqjj for reporting.
can you please have a look at the fix?
https://github.com/codingsince1985/checksum/pull/4/files

**Comment by codingsince1985** [comment]
thanks again @jqqjj
i've merged to master and tagged as v1.3.0
please feel free to close this issue once it works for you
