### ISSUE TITLE
Fix version tag

### ISSUE THREAD

**Issue by vinicius73** [codingsince1985/checksum#5]
The latest tag is `1.3.0`, but it should be `v1.3.0`

Go can't find the latest version

https://pkg.go.dev/github.com/codingsince1985/checksum?tab=versions
https://pkg.go.dev/github.com/codingsince1985/checksum@v1.3.0
https://pkg.go.dev/github.com/codingsince1985/checksum@1.3.0

**Comment by codingsince1985** [comment]
thanks for heads-up, @vinicius73.
it's now tagged correctly.
